### ISSUE TITLE
A small feature

### ISSUE THREAD

**Issue by kingc2022** [devmahmud/Django-Poll-App#18]
# A small feature

## I think you can add a small feature about:

```
The user who initiated the vote can view the vote in real time
```

```
Users who have voted can view the vote in real time
```

## Thank you very much!

**Comment by kingc2022** [comment]
Hi,
I mean in real time,
```
Administrators can view vote counts even if they have not voted.
Ordinary users can view the results in real time when they voted.
```
Thanks!

**Comment by devmahmud** [comment]
This feature can be implemented using long polling or a web socket(Django channel). Because this is heavily focused on beginners we should skip WS. Thanks for your suggestion. I will implement long polling so that it feels like real-time.

**Comment by toukirkhan** [comment]
@devmahmud I want to use this project for my college assignment can you please help me with it?

**Comment by Eniiyanu** [comment]
What assist do you need?

**Comment by AdityaB09** [comment]
Here I have added  <meta http-equiv="refresh" content="5"> in base html template file. This facilitates checking on the result tab if another user votes in real time.We need to be sure that this tag is not applicable to all the html files as it can create a problem of ephemeral data. Html page will reload every 5 seconds. User will get the real time voting experience. Another method by which we can apply this phenomena is Django Web sockets and Production Mode.
