### ISSUE TITLE
Functionality call to action

### ISSUE THREAD

**Issue by akshayaureatelabs** [devmahmud/Django-Poll-App#21]
Hi @devmahmud. 
Delete Functionality is not working properly. This means that after delete operations, it needs to redirect back to the `.../polls/list/user/` page. It's getting stuck on that particular page. Also, I have given an attachment regarding this issue.
[CTA.webm](https://user-images.githubusercontent.com/117964113/218978503-f84c86fc-71da-4543-9355-91e8507af5a8.webm)

Note: This issue is occur in all calls to action or CTA.

Thank you.

**Comment by AdityaB09** [comment]
we can modify the poll_delete function 👍 @login_required
def polls_delete(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.user != poll.owner:
        return redirect('home')
    else :
     poll.delete()
       all_polls = Poll.objects.all()
    search_term = ''
    if 'name' in request.GET:
        all_polls = all_polls.order_by('text')

    if 'date' in request.GET:
        all_polls = all_polls.order_by('pub_date')

    if 'vote' in request.GET:
        all_polls = all_polls.annotate(Count('vote')).order_by('vote__count')

    if 'search' in request.GET:
        search_term = request.GET['search']
        all_polls = all_polls.filter(text__icontains=search_term)


    paginator = Paginator(all_polls, 6)  # Show 6 contacts per page
    page = request.GET.get('page')
    polls = paginator.get_page(page)

    get_dict_copy = request.GET.copy()
    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()
    print(params)
    context = {
        'polls': polls,
        'params': params,
        'search_term': search_term,
    }
    
     messages.success(request, "Poll Deleted successfully.",
                     extra_tags='alert alert-success alert-dismissible fade show')
     return render(request, 'polls/polls_list.html', context)

This will give the resultant url as 127.0.0.1:8000/polls/delete/poll_number
