### ISSUE TITLE
Naming Convection mistake.

### ISSUE THREAD

**Issue by ArManiyar** [devmahmud/Django-Poll-App#22]
Naming Convention mistake while retriving the users from User table in seeder.py file

def seed_users(num_entries=10, overwrite=False):
    """
    Creates num_entries worth a new users
    """
    if overwrite:
        print("Overwriting Users")
        Users.objects.all().delete()   ## User should be there instead of Users
    count = 0
    for _ in range(num_entries):
        first_name = fake.first_name()
        last_name = fake.last_name()
        u = User.objects.create_user(
            first_name=first_name,
            last_name=last_name,
            email=first_name + "." + last_name + "@fakermail.com",
            username=first_name + last_name,
            password="password"
        )
        count += 1
        percent_complete = count / num_entries * 100
        print(
            "Adding {} new Users: {:.2f}%".format(
                num_entries, percent_complete),
            end='\r',
            flush=True
        )
    print()

**Comment by devmahmud** [comment]
The issue was fixed in this [PR](https://github.com/devmahmud/Django-Poll-App/pull/23). Thanks!
